FiniteMatrix::finiteMat AE(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat AW(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat AS(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat AN(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat AP(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat SU(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat SV(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat APU(NI,vector<FiniteMatrix>(NJ));
FiniteMatrix::finiteMat APV(NI,vector<FiniteMatrix>(NJ));